apiVersion: v1
kind: Service
metadata:
  name: nginxservice
  annotations:
    # These annotations are only required for cluster templates <=1.18
    loadbalancer.openstack.org/network-id: "a17e0944-5131-4efc-afb1-40a4563cd7b9"
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
    loadbalancer.openstack.org/cascade-delete: "false"
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer
