apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleaner
  labels:
    k8s-app: cleaner
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cleaner
  template:
    metadata:
      labels:
        k8s-app: cleaner
    spec:
      containers:
        - name: cleaner
          image: ivukotic/vpservice:expunge
          # command: ["./start.sh"]
          command: ["sleep"]
          args: ["99999999"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 500Mi
          env:
            - name: RUCIO_ACCOUNT
              value: "ivukotic"
            - name: X509_USER_PROXY
              value: "/tmp/x509up_u0"
          volumeMounts:
            - name: certs-volume
              mountPath: "/etc/grid-certs/"
              readOnly: true
      volumes:
        - name: certs-volume
          secret:
            secretName: cert-secret
            items:
              - key: userkey
                path: userkey.pem
                mode: 256
              - key: usercert
                path: usercert.pem
