apiVersion: batch/v1
kind: Job
metadata:
  name: simple-cleaner
spec:
  template:
    spec:
      containers:
        - name: cleaner
          image: ivukotic/vpservice:cleanup
          command: ["sleep"]
          args: ["99999999"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 500Mi
      restartPolicy: Never
