image:
  repository: ivukotic
  pullPolicy: Always
  tag: "latest"

frontend:
  replicaCount: 1
  port: 80
  domain: ilija-z42lmh2tqlys-node-0.cern.ch

filler:
  replicaCount: 2

redis:
  persistence:
    existingClaim:
      cinder:
        volumeID: b583a2ab-8ebb-493d-862d-822912944526
        fsType: ext4
