apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-standard
provisioner: cinder.csi.openstack.org
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: "Standard"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vp-open-cinder-vol
spec:
  storageClassName: cinder-standard-delete
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
