kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vp-manila-vol
spec:
  storageClassName: meyrin-cephfs-vault-ssd-a
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
