apiVersion: v1
kind: Secret
metadata:
  name: config
type: Opaque
data:
  config.json: ewogICAgIlBPUlQiOiA2Mzc5LAogICAgIkhPU1QiOiAicmVkaXMtbWFzdGVyLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLAogICAgIlBSRUNBTENVTEFURURfTFdNIjogMTAwMCwKICAgICJQUkVDQUxDVUxBVEVEX0hXTSI6IDMwMDAsCiAgICAiTiI6IDUsCiAgICAiQkFDS1VQX0lOVEVSVkFMIjogMywKICAgICJMSUZFVElNRV9JTlRFUlZBTCI6IDE4MCwKICAgICJURVNUSU5HIjogZmFsc2UKfQ==
