apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.json: |
    {
      "PORT": 6379,
      "HOST": "redis-master.default.svc.cluster.local",
      "PRECALCULATED_LWM": 1000,
      "PRECALCULATED_HWM": 3000,
      "N": 5,
      "BACKUP_INTERVAL": 3,
      "LIFETIME_INTERVAL": 180,
      "TESTING": false
    }