apiVersion: v1
kind: Service
metadata:
  name: vps
  labels:
    k8s-app: vps
spec:
  type: NodePort
  ports:
    - nodePort: 30149
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    k8s-app: vps
