apiVersion: v1
kind: Service
metadata:
  name: vps
  labels:
    k8s-app: vps
spec:
  type: NodePort
  ports:
    - nodePort: 30149
      port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    k8s-app: vps
