openapi: 3.0.0
info:
  version: 1.0.0
  title: Topology
  contact:
    name: Ilija Vukotic
    url: https://github.com/ivukotic/VPservice
    email: ivukotic@uchicago.edu
servers:
  - url: "http://localhost:3000"
paths:
  /healthz:
    get:
      summary: "For a liveness probe. Returns version."
      responses:
        "200":
          description: "Returns version of code."
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
#   /liveness:
#     post:
#       summary: 'For XCache servers to report to. Send basic info.'
#       requestBody:
#         description: XCache object in JSON format
#         required: true
#         content:
#           application/json:
#             schema:
#               $ref: '#/components/schemas/XCacheServer'
#               example:
#                 id: mwt2_1
#                 site: mwt2
#                 address: xcache1.mwt2.org
#       responses:
#         "200":
#           description: 'Returns OK.'
#           content:
#             text/plain:
#               schema:
#                 type: string
#               example: OK
#         default:
#           description: Unexpected error
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/Error'
#     # /prefix:
#     #     get:
#     #         summary: For a client to ask for a xcache to use.
#     #         # parameters:
#     #         # - name: client
#     #             # description: "client name. Can be ATLAS DDM endpoint, site, analysis farm"
#     #         #   in: "query"
#     #             # required: true
#     #             # schema:
#     #             #     type: string
#     #             # example: MWT2_SCRATCHDISK
#     #             # filename:
#     #             #     description: filename to be looked for
#     #             #     in: query
#     #             #     required: true
#     #             #     schema:
#     #             #         type: string
#     #             #     example: scope:xAOD.123.23.root
#     #         responses:
#     #             '200':
#     #                 description: 'Returns address of the XCache server.'
#     #                 content:
#     #                     text/plain:
#     #                         example: root://xcache3.mwt2.org:1094
#     #             '500':
#     #                 description: 'Missing parameter'
# components:
#     schemas:
#         Version:
#             type: string
#             description: "server & api version"
#         XCacheServer:
#             type: object
#             required:
#                 - id
#                 - address
#                 - size
#             properties:
#                 id:
#                     type: string
#                     description: "ID of the server."
#                 site:
#                     type: string
#                     description: "site that xcache server belongs to."
#                 address:
#                     type: string
#                     description: "FQDN or IP of xcache server."
#                 size:
#                     type: integer
#                     format: int64
#                     description: "Total server disk space in MB."
#         Error:
#         type: object
#         required:
#             - code
#             - message
#         properties:
#             code:
#             type: integer
#             format: int32
#             message:
#             type: string
#     # parameters:
#     #     xc_site:
#     #         type: string
#     #         description: "site that xcache server belongs to."
