openapi: 3.0.0

info:
  version: 1.0.0
  title: Topology
  contact:
    name: Ilija Vukotic
    url: https://github.com/ivukotic/VPservice
    email: ivukotic@uchicago.edu

servers:
  - url: "http://localhost:3000"

paths:

  /healthz:
    get:
      summary: For a liveness probe. Returns version.
      responses:
        200:
          description: Returns OK.
          content:
            text/plain:
              schema:
                type: string
              example: OK
        default:
          $ref: '#/components/responses/GeneralError'

  /liveness:
    post:
      summary: For XCache servers to report to. Send basic info.
      requestBody:
        description: XCache object in JSON format
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XCacheServer'
            examples:  
              grid_site:
                summary: grid site deployed cache example
                value: 
                  id: xc1
                  site: MWT2
                  address: xc1.mwt2.org
                  size: 123123123
              in_network_cache:
                summary: in network cache
                value: 
                  id: xc_esnet
                  site: Sunnyvale
                  address: xc_esnet.asd.org
      responses:
        200:
          description: Returns OK.
          content:
            text/plain:
              schema:
                type: string
              example: OK
        default:
          $ref: '#/components/responses/GeneralError'

  /prefix:
    get:
      summary: For a client to ask for a xcache to use.
      responses:
        200:
          description: Returns address of the XCache server.
          content:
            text/plain:
              example: root://xcache3.mwt2.org:1094
        500:
          $ref: '#/components/responses/IllegalInput'
        default:
          $ref: '#/components/responses/GeneralError'
    parameters:
    - $ref: '#/components/parameters/client'
    - $ref: '#/components/parameters/filename'

  /serve:
    put:
      summary: For a VP operator to allow the xcache site to serve the client.
      parameters:
      - $ref: '#/components/parameters/client'
        required: false
      - $ref: '#/components/parameters/site'
        required: false
      responses:
        200:
          description: Always succesuccessful.
          content:
            text/plain:
              schema:
                type: string
              example: OK
        default:
          $ref: '#/components/responses/GeneralError'
    get:
      summary: Returns serving pairs. If cache site and/or client given only ones matching the request are returned.
      responses:
        200:
          description: returns pairs as json array
          content:
            text/plain:
              schema:
                type: string
              example: OK
        default:
          $ref: '#/components/responses/GeneralError' 
      parameters:
      - $ref: '#/components/parameters/client'
        required: false
      - $ref: '#/components/parameters/site'
        required: false
    delete:
      summary: Dissalows the xcache site to serve the client.
      responses:            
        200:
          description: Always succesuccessful.
          content:
            text/plain:
              schema:
                type: string
              example: OK
        default:
          $ref: '#/components/responses/GeneralError'
      parameters:
      - $ref: '#/components/parameters/client'
      - $ref: '#/components/parameters/site'
components:
  
  schemas:

    Version:
      type: string
      description: "server & api version"

    XCacheServer:
      type: object
      required:
        - id
        - site
        - address
      properties:
        id:
          type: string
          description: ID of the server.
          example: xcache_dfnu4dfv4_2ed8f
        site:
          type: string
          description: site that xcache server belongs to.
          example: MWT2_Caches
        address:
          type: string
          description: FQDN or IP of xcache server.
          example: xcache1.mwt2.org
        size:
          type: integer
          format: int64
          description: Total server disk space in MB.
          minimum: 0
          example: 123123123123

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  
  parameters:
    client:
      name: client
      description: client name. Can be ATLAS DDM endpoint, site, analysis farm
      in: query
      required: true
      schema:
        type: string
      example: MWT2_SCRATCHDISK
    filename:
      name: filename
      description: filename to be looked for
      in: query
      required: true
      schema:
        type: string
      example: scope:xAOD.123.23.root
    site:
      name: site
      description: xcache site
      in: query
      required: true
      schema:
        type: string
      example: MWT2_xcache

  responses:
    IllegalInput: 
      description: Illegal input for operation.
    GeneralError: 
      description: General Error
      content: 
        application/json: 
          schema: 
            $ref: "#/components/schemas/Error"
