image:
  repository: ivukotic
  pullPolicy: Always
  tag: "latest"

frontend:
  replicaCount: 1
  port: 80

filler:
  replicaCount: 2

redis:
  persistence:
    existingClaim:
      cinder:
        volumeID: 028c046b-d61d-47fd-b3d5-e4c999cf6fe1
        fsType: ext4
